version: '3.9'
services:
  mongodb: 
    image: mongo
    container_name: mongodb_container
    ports:
     - ${DB_PORT}:${DB_PORT}
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
  # mongo-ui:
  #   image: mongo-express
  #   container_name: mongodb_ui
  #   ports:
  #    - 8080:8081
  #   environment:
  #   #  - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
  #   #  - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
  #    - ME_CONFIG_MONGODB_SERVER=mongodb
  cooks-cabinet:
    image: cooks-cabinet
    container_name: cooks-cabinet
    ports:
     - ${PORT}:${PORT}
    restart: always
    build: .
  